[build]
  command = "yarn bootstrap && yarn build"
  functions = "lambda"
  publish = "apps/subocean-tiger-web/out"

[build.environment]
  JSON_PLACEHOLDER_URL = "https://jsonplaceholder.typicode.com"
  GRAPHQL_SERVER_URL = "/.netlify/functions/index"

[context.production.environment]
  JSON_PLACEHOLDER_URL = "https://jsonplaceholder.typicode.com"
  GRAPHQL_SERVER_URL = "/.netlify/functions/index"
